### PR TITLE
Add a pyfakefs/ module directory; include README.md and COPYING files

### PR DESCRIPTION
**Pull request by jcwilson**
This should enable PyPi usage.

### CODE REVIEW

**Comment by jcwilson** [comment]
For #45 and #64

**Comment by jcwilson** [comment]
I was able to test this by doing:
```
$ python setup.py sdist
$ pip install file:///shared/pyfakefs/dist/pyfakefs-2.6.tar.gz#egg=pyfakefs-2.6
```

**Comment by jmcgeheeiv** [comment]
I have been looking into this.  I created a MANIFEST.in:

more MANIFEST.in
include README.md
include COPYING
include __init__.py

Do note that in the current uploaded version, __init__.py is missing.
However, it is my understanding that putting a file in MANIFEST.in does not
get it installed.  I have to figure out that as well.

**Comment by jcwilson** [comment]
added those in, too

**Comment by jcwilson** [comment]
interesting, i guess the docs are a little misleading about having to explicitly name the rest of your files.  Seems like your slimmed-down one suffices. Let's go with that

**Comment by jmcgeheeiv** [comment]
Did you install this and observe that `__init__.py` is *installed*?

**Comment by jcwilson** [comment]
the way this is being installed is that each of the `fake_*` files are being copied directly into site-packages (along with pyfakefs-2.6-py2.7.egg-info being created there). The `__init__.py` is irrelevant in this distribution manner. If we wanted to treat it as an actual package, we'd need to have another directory (named `pyfakefs`) in the repo and move the `fake_*` files into there. I can take a stab at that, but it will be an interface-breaking change for any current users that attempt a simple upgrade.

the usage would become something like:
```
from pyfakefs import fake_filesystem_unittest
```

**Comment by jmcgeheeiv** [comment]
Yes, the absence of a pyfakefs/ directory causes pain in several ways.  I think it's worth breaking existing installations to add the directory.

**Comment by jcwilson** [comment]
most of the tests pass. i think I can chalk the failures up to my running them from cygwin and using nosetests. I'm not sure what test runner you're using.

**Comment by jmcgeheeiv** [comment]
Travis and I run all_tests.py.  I have heard reports of weirdness with Cygwin.

Anyway, if you got most of the tests to run and pass, that is a fine test of the installation.  I'll upload pyfakefs again.

**Comment by jmcgeheeiv** [comment]
Very nice.  Thanks for taking care of that.

Could you please fix this test failure?

$ ./all_tests.py
Traceback (most recent call last):
  File "./all_tests.py", line 21, in <module>
    import fake_filesystem_glob_test
  File "/home/travis/build/jmcgeheeiv/pyfakefs/fake_filesystem_glob_test.py", line 27, in <module>
    from pyfakefs import fake_filesystem_glob
  File "/home/travis/build/jmcgeheeiv/pyfakefs/pyfakefs/fake_filesystem_glob.py", line 38, in <module>
    import fake_filesystem
ImportError: No module named fake_filesystem
The command "./all_tests.py" exited with 1.
Done. Your build exited with 1.

**Comment by jcwilson** [comment]
i think i fixed that, but there's something going on with the doc tests. Unfortunately, i don't have python 3 handy, and i'm not familiar enough with the doctest functionality to say why it's failing now.

**Comment by jcwilson** [comment]
want me to collapse these into one commit?

**Comment by jmcgeheeiv** [comment]
If it's not too much trouble.  Let me know and I'll pull your fork and deal
with the doctest/Python3 issue.

**Comment by jcwilson** [comment]
no trouble at all. seems like all the tests are passing now, too :)

also, if you think it's appropriate, you can add `exclude pyfakefs/example.py` to the manifest file to ensure it doesn't ship when installing

**Comment by jcwilson** [comment]
I relocated the `example.py` file back to the top-level directory, since it's not something that should really be considered part of the package

**Comment by jmcgeheeiv** [comment]
Nice work, @jcwilson.  I uploaded this as pyfakefs 2.7.  Please give it a try.

**Pull request merged**
