### PR TITLE
Adding followlinks parameter to os.walk includes test

### PR DESCRIPTION
**Pull request by julianhille**

### CODE REVIEW

**Comment by julianhille** [comment]
any news on this? :)

**Comment by julianhille** [comment]
Is this repo dead?

**Comment by mrbean-bremen** [comment]
The owner is active on other repos, so I hope it is just a matter of time...

**Comment by jmcgeheeiv** [comment]
Thank you for the pull request.  I reviewed the code, and if you would, could you add a test that verifies that the default for the `followlinks` argument is `False`.

I apologize for the delay.

**Comment by jmcgeheeiv** [comment]
Oops.  Pushed the wrong button.  Reopening.

**Comment by julianhille** [comment]
@jmcgeheeiv im sorry but i don't get why another test for the default case is needed as there was already a test for  it and this one just runs as before.
Do i miss something?

```def testWalk(self):```

from lines [1992](https://github.com/jmcgeheeiv/pyfakefs/pull/71/commits/ff13a70b39285b204da8a41a5249654d88bf9038#diff-96dc229ce2ed060988dd7c7701f47120L1991)

**Comment by jmcgeheeiv** [comment]
Ah.  Forgive me.  There it is right there.

**Comment by julianhille** [comment]
thank you

**Pull request merged**
