### PR TITLE
Set initial user and group IDs to real IDs

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- added tests running as root to test both root and non-root cases
- adapted code and tests to consider root access

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
I have one test failing in Python 3.7. I tried to skip it, but for some reason that does not work with root user.

**Comment by jmcgeheeiv** [comment]
Instead of using sudo, we can use my Docker container method to run the test as root without endangering the host.

**Comment by mrbean-bremen** [comment]
> Instead of using sudo, we can use my Docker container method to run the test as root without endangering the host.

The problem with the Docker image is that it runs only one Python version - or we have to configure it accordingly for each version. That is actually what Travis.CI does for us, and as it runs in cloned VMs that are trashed after the tests, there is no problem with endangering the host (otherwise they wouldn't provide sudo without password...).
Though as I wrote elsewhere, it would be a good idea also to run the tests in the provided Docker image to make sure that it works correctly.

My problem was that I got the wrong environment if run with sudo, so the system python (Python 2.7) was used instead of the Python version installed in the virtual environment. Inheriting PATH fixed this.

**Comment by mrbean-bremen** [comment]
Merging after resolviong conflicts again...

**Pull request merged**
