### PR TITLE
add Python 3.9 and 3.10 to tox.ini

### PR DESCRIPTION
**Pull request by okken**
Tested changes with `tox -e py39,py310' and tests pass.

### CODE REVIEW

**Review by mrbean-bremen — COMMENTED** [review]
Thanks - can you please also remove `py35` and change `pypy` to `pypy3` to be up-to-date? I obviously forgot to update this file.

**Comment by okken** [comment]
sure.

**Comment by okken** [comment]
ok. I made the changes.
When I tried to run `tox -e pypy3`, I ran into some issues.
But it might be my setup.

**Review by mrbean-bremen — APPROVED** [review]
Thanks!

**Pull request merged**
